version: '3.4'

services:
  minapi:
    image: ${DOCKER_REGISTRY-}gdswithrest
    build:
      context: .
      dockerfile: GDSwithREST/Dockerfile
    ports:
        - "8080:80"
        - "8081:443"
        - "58810:58810"
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"
    environment:
        MSSQL_SA_PASSWORD: "jeh7he89u534758Ghe54"
        ACCEPT_EULA: "Y"

