name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./GDSwithREST/Dockerfile --tag gdswithrest:$(date +%s)

    - name: Rename Docker image
      run: docker tag gdswithrest:$(date +%s) ghcr.io/romanett/gdswithrest:$(date +%s)

    - name: Login with Github Container registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to Github Container registry
      run: docker push ghcr.io/romanett/gdswithrest:$(date +%s)
